// <auto-generated />
using System;
using AVMLabs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVMLabs.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVMLabs.Api.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientName");

                    b.HasIndex("Country");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clients_CreditLimit", "[CreditLimit] > 0");
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WOId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ClientId");

                    b.HasIndex("WOId");

                    b.ToTable("Invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_DueDate", "[DueDate] >= [InvoiceDate]");

                            t.HasCheckConstraint("CK_Invoices_Status", "[Status] IN ('Pending', 'Paid', 'Overdue')");

                            t.HasCheckConstraint("CK_Invoices_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("GatewayFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentDate");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_GatewayFee", "[GatewayFee] >= 0");

                            t.HasCheckConstraint("CK_Payments_Mode", "[Mode] IN ('Cash', 'Cheque', 'Online')");

                            t.HasCheckConstraint("CK_Payments_NetAmount", "[NetAmount] >= 0");
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TATHours")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TestId");

                    b.HasIndex("TestCode")
                        .IsUnique();

                    b.ToTable("Tests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tests_Rate", "[Rate] >= 0");

                            t.HasCheckConstraint("CK_Tests_TATHours", "[TATHours] > 0");
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrder", b =>
                {
                    b.Property<int>("WOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WOId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("WODate")
                        .HasColumnType("date");

                    b.HasKey("WOId");

                    b.HasIndex("ClientId");

                    b.HasIndex("WODate");

                    b.ToTable("WorkOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkOrders_Status", "[Status] IN ('Pending', 'Processing', 'Reported', 'Billed')");

                            t.HasCheckConstraint("CK_WorkOrders_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrderItem", b =>
                {
                    b.Property<int>("WOItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WOItemId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("WOId")
                        .HasColumnType("int");

                    b.HasKey("WOItemId");

                    b.HasIndex("SampleStatus");

                    b.HasIndex("TestId");

                    b.HasIndex("WOId");

                    b.ToTable("WorkOrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkOrderItems_Amount", "[Amount] = [Quantity] * [Rate]");

                            t.HasCheckConstraint("CK_WorkOrderItems_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_WorkOrderItems_Rate", "[Rate] >= 0");

                            t.HasCheckConstraint("CK_WorkOrderItems_SampleStatus", "[SampleStatus] IN ('Received', 'InTransit')");
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Invoice", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVMLabs.Api.Models.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Payment", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Client", "Client")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrderItem", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Test", "Test")
                        .WithMany("WorkOrderItems")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVMLabs.Api.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderItems")
                        .HasForeignKey("WOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Test", b =>
                {
                    b.Navigation("WorkOrderItems");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrder", b =>
                {
                    b.Navigation("WorkOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
